dataset_path: "./datasets/robot_LLM_reason_dataset_30k/mixed"
test_size: 0.03

model_name: "meta-llama/Llama-3.2-3B-Instruct"

bnb_config:
  load_in_4bit: true
  bnb_4bit_compute_dtype: "float16"
  bnb_4bit_quant_type: "nf4"

lora_config:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"

training:
  output_dir: "./datasets/llama-3.2-3b-finetuned_CoT"
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  num_train_epochs: 5
  save_strategy: "steps"
  save_steps: 400
  save_total_limit: 10
  logging_dir: "./datasets/logs"
  logging_steps: 1
  report_to: "tensorboard"
  evaluation_strategy: "steps"
  per_device_eval_batch_size: 1
  eval_steps: 200
  learning_rate: 2e-5
  weight_decay: 0.01
  warmup_steps: 100
  fp16: true
  max_length: 8192
  packing: false
