env:
  name: "BabyAI-GoToRedBallGrey-v0"
  procs: 32

model:
  patch_size: 1
  embed_dim: 64
  num_heads: 2
  num_layers: 2

training:
  log_loss: true
  algo: "ppo"
  model_name: "trans_test4"
  seed: 1
  frames: 10000000
  log_interval: 1
  save_interval: 10
  epochs: 4
  batch_size: 256
  frames_per_proc: 64
  discount: 0.99
  lr: 0.00001
  gae_lambda: 0.95
  entropy_coef: 0.01
  value_loss_coef: 0.5
  max_grad_norm: 0.5
  optim_eps: 1e-8
  optim_alpha: 0.99
  clip_eps: 0.2
  recurrence: 1
  text: False